In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Set up TensorFlow

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


# Load a dataset

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


# Build a machine learning model

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 1.0861593 , -0.6442407 ,  0.00163483,  0.19729845, -0.4587751 ,
         0.17601275,  0.29342866,  0.00441894, -1.045776  , -0.03783394]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()


array([[0.26473305, 0.04691427, 0.08949631, 0.10883806, 0.0564744 ,
        0.10654584, 0.11982008, 0.08974583, 0.03139933, 0.0860328 ]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.2391798

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# Train and evaluate your model

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2946 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1442 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1085 - accuracy: 0.9665
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0902 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0766 - accuracy: 0.9755


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0729 - accuracy: 0.9754 - 866ms/epoch - 3ms/step


[0.07286613434553146, 0.9753999710083008]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.25353141e-08, 1.59779603e-08, 9.84544113e-06, 2.58323533e-04,
        3.76689478e-12, 2.03538502e-08, 7.38131869e-15, 9.99726713e-01,
        1.17917331e-07, 4.84888551e-06],
       [3.43967010e-09, 7.89649494e-05, 9.99895096e-01, 2.54172646e-05,
        7.27195996e-15, 4.01057406e-07, 4.71997197e-09, 3.37962731e-12,
        1.75540336e-07, 1.31770853e-11],
       [5.10620612e-09, 9.99769747e-01, 2.34947674e-05, 9.69140274e-07,
        9.40322752e-06, 1.48818472e-07, 1.09212469e-05, 9.99195836e-05,
        8.52716548e-05, 6.55245103e-08],
       [9.99163866e-01, 1.08375255e-08, 6.40764483e-04, 2.54258066e-06,
        1.58802902e-06, 3.67725875e-06, 1.21174871e-05, 1.42449135e-04,
        1.18733020e-07, 3.29581344e-05],
       [8.15259773e-06, 3.47631897e-08, 2.98281429e-06, 2.82833696e-07,
        9.84814346e-01, 5.34712171e-07, 6.27900181e-06, 1.17653901e-04,
        8.66082019e-07, 1.50489677e-02]], dtype=float32)>