In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Set up TensorFlow

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


# Load a dataset

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


# Build a machine learning model

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.30459166, -0.6199203 ,  0.54208046, -0.57445407,  0.3092195 ,
         0.24618846,  0.3645942 , -0.48405588, -0.5603012 , -0.9089959 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()


array([[0.07989707, 0.05828883, 0.18630987, 0.06100018, 0.14760655,
        0.1385899 , 0.15601076, 0.0667714 , 0.06186964, 0.04365574]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

1.976236

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# Train and evaluate your model

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2965 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1443 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1080 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0899 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0747 - accuracy: 0.9768


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0794 - accuracy: 0.9760 - 608ms/epoch - 2ms/step


[0.07936632633209229, 0.9760000109672546]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.4840071e-08, 4.7069690e-09, 2.4163787e-06, 3.2405464e-05,
        1.1832392e-12, 1.8444275e-07, 8.4459777e-13, 9.9996126e-01,
        1.8777318e-07, 3.4551354e-06],
       [2.4113326e-08, 8.5306256e-06, 9.9994993e-01, 3.9550989e-05,
        2.1590804e-17, 5.5076521e-07, 2.7487210e-09, 6.0305154e-15,
        1.4106516e-06, 6.2565784e-14],
       [1.3213220e-07, 9.9840313e-01, 7.4188792e-05, 3.2170603e-05,
        1.0397107e-04, 1.8387844e-05, 1.0666016e-05, 6.5763178e-04,
        6.9947413e-04, 2.4881646e-07],
       [9.9997652e-01, 2.5262675e-13, 2.2334760e-05, 2.9164772e-08,
        4.7251641e-10, 5.0328619e-08, 5.3735494e-07, 2.9578375e-08,
        4.9801437e-11, 5.2148732e-07],
       [2.6323787e-07, 8.2856344e-10, 2.2356489e-06, 3.5540939e-08,
        9.9902737e-01, 5.9833832e-07, 5.4563247e-07, 6.5416418e-05,
        1.1706676e-06, 9.0239575e-04]], dtype=float32)>